export enum Language {
  '' = 'plain text',
  html = 'html',
  css = 'css',
  javascript = 'javascript',
  typescript = 'typescript',
  tsx = 'tsx',
  vue = 'vue',
  java = 'java',
  c = 'c',
  python = 'python',
  ruby = 'ruby',
  sql = 'sql',
  go = 'go',
  markdown = 'markdown',
  json = 'json',
}
